### PR TITLE
Fixed build on OpenBSD

### PR DESCRIPTION
**Pull request by catap**
This fixes https://github.com/docker/buildx/issues/2772

### CODE REVIEW

**Review by tonistiigi — APPROVED** [review]
We should add this to CI as well. If the tests can't run, then at least check that it builds.

**Comment by tonistiigi** [comment]
https://github.com/tonistiigi/fsutil/blob/master/docker-bake.hcl#L90

**Comment by catap** [comment]
@tonistiigi seems that it requires a bit more work what just add it into this file. At least I see that dedicated instance with VM via vargand is required.

**Comment by tonistiigi** [comment]
Vagrant would be needed to run the tests. To just check that code builds doesn't need it.

**Comment by catap** [comment]
Here my attempt: https://github.com/catap/fsutil/tree/openbsd-ci

if you think that it’s enough I ready to open PR

**Comment by catap** [comment]
Tuis, I had run it as: https://github.com/catap/fsutil/actions/runs/11635591513

**Pull request merged**
