### PR TITLE
Fixes an error propagation bug that resulted in a hang

### PR DESCRIPTION
**Pull request by tiborvass**
Signed-off-by: Tibor Vass <tibor@docker.com>

### CODE REVIEW

**Comment by tonistiigi** [comment]
@tiborvass pushed an extra commit

**Comment by tiborvass** [comment]
Tested in buildkit, LGTM

**Comment by tonistiigi** [comment]
LGTM

**Comment by tonistiigi** [comment]
@tiborvass There is a slight problem with this test that showed in CI. If the receiver isn't blocked when the walker errors, the receiver would close directly from `ctx.Done()`, without doing the roundtrip. I think this behavior is ok, but the error doesn't have the `from sender` prefix then.

**Pull request merged**
