### PR TITLE
Implement chtimes on OpenBSD

### PR DESCRIPTION
**Pull request by nogoegst**

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @tonistiigi PTAL

**Comment by tonistiigi** [comment]
This could probably be in the `_nolinux.go` file with `!linux` build tag so there is no duplication with windows and darwin.

**Comment by nogoegst** [comment]
@tonistiigi, it seems that `chtimes` is not implemented on darwin. :man_shrugging:

**Comment by tonistiigi** [comment]
@nogoegst You mean `os.Chtimes` ? It definitely should be. https://github.com/golang/go/blob/6732fcc06df713fc737cee5c5860bad87599bc6d/src/os/file_posix.go#L5 https://github.com/golang/go/blob/6732fcc06df713fc737cee5c5860bad87599bc6d/src/os/file_posix.go#L139

So just to be clear, linux has own implementation. I think everything but linux can use `os.Chtimes` solution like suggested in here, instead of defining per-platform exceptions.

**Comment by nogoegst** [comment]
Closing in favor of #27.

**Pull request closed without merging**
