### PR TITLE
ci: freebsd job enhancements

### PR DESCRIPTION
**Pull request by crazy-max**
related to: https://github.com/tonistiigi/fsutil/actions/runs/7375943482/job/20068119491#step:4:30

image

This is similar to what has been done on buildkit repo:
* https://github.com/moby/buildkit/pull/4486
* https://github.com/moby/buildkit/pull/4363
* https://github.com/moby/buildkit/pull/4147
* https://github.com/moby/buildkit/pull/4378

### CODE REVIEW

**Comment by crazy-max** [comment]
This test failing is really odd: https://github.com/tonistiigi/fsutil/actions/runs/7423884290/job/20202299898?pr=172#step:7:1047

```
     fbsd_13_2: === RUN   TestStat
    fbsd_13_2:     stat_test.go:49:
    fbsd_13_2:         	Error Trace:	/vagrant/stat_test.go:49
    fbsd_13_2:         	Error:      	Not equal:
    fbsd_13_2:         	            	expected: &types.Stat{state:impl.MessageState{NoUnkeyedLiterals:pragma.NoUnkeyedLiterals{}, DoNotCompare:pragma.DoNotCompare{}, DoNotCopy:pragma.DoNotCopy{}, atomicMessageInfo:(*impl.MessageInfo)(nil)}, sizeCache:0, unknownFields:[]uint8(nil), Path:"dd", Mode:0x80001ff, Uid:0x0, Gid:0x0, Size:6, ModTime:0, Linkname:"../../", Devmajor:0, Devminor:0, Xattrs:map[string][]uint8(nil)}
    fbsd_13_2:         	            	actual  : &types.Stat{state:impl.MessageState{NoUnkeyedLiterals:pragma.NoUnkeyedLiterals{}, DoNotCompare:pragma.DoNotCompare{}, DoNotCopy:pragma.DoNotCopy{}, atomicMessageInfo:(*impl.MessageInfo)(nil)}, sizeCache:0, unknownFields:[]uint8(nil), Path:"dd", Mode:0x80001ed, Uid:0x0, Gid:0x0, Size:6, ModTime:0, Linkname:"../../", Devmajor:3886, Devminor:188974, Xattrs:map[string][]uint8(nil)}
    fbsd_13_2: 
    fbsd_13_2:         	            	Diff:
    fbsd_13_2:         	            	--- Expected
    fbsd_13_2:         	            	+++ Actual
    fbsd_13_2:         	            	@@ -13,3 +13,3 @@
    fbsd_13_2:         	            	  Path: (string) (len=2) "dd",
    fbsd_13_2:         	            	- Mode: (uint32) 134218239,
    fbsd_13_2:         	            	+ Mode: (uint32) 134218221,
    fbsd_13_2:         	            	  Uid: (uint32) 0,
    fbsd_13_2:         	            	@@ -19,4 +19,4 @@
    fbsd_13_2:         	            	  Linkname: (string) (len=6) "../../",
    fbsd_13_2:         	            	- Devmajor: (int64) 0,
    fbsd_13_2:         	            	- Devminor: (int64) 0,
    fbsd_13_2:         	            	+ Devmajor: (int64) 3886,
    fbsd_13_2:         	            	+ Devminor: (int64) 188974,
    fbsd_13_2:         	            	  Xattrs: (map[string][]uint8) <nil>
```

Could it be linked to macos-13 runner? cc @akhramov

**Comment by akhramov** [comment]
https://github.com/tonistiigi/fsutil/blob/797bd683d5a28a87bea5421f51db1e112ac2edd4/receive_test.go#L511-L513

it reminds me of this ^. I wonder if the test ever worked.

**Comment by crazy-max** [comment]
> it reminds me of this ^. I wonder if the test ever worked.

It looks good on main branch: https://github.com/tonistiigi/fsutil/actions/runs/7369259860/job/20054368194#step:5:19

**Comment by crazy-max** [comment]
> https://github.com/tonistiigi/fsutil/blob/797bd683d5a28a87bea5421f51db1e112ac2edd4/receive_test.go#L511-L513
> 
> it reminds me of this ^. I wonder if the test ever worked.

Ok I think I found the issue. Seems to repro only when running through a subshell with Vagrant provisioning. That's really odd.

**Review by tonistiigi — APPROVED** [review]

**Pull request merged**
